package constants

// 日志模板集中管理（≥25 条）。业务字段变更时必须同步修改模板与调用处。
const (
	LogServerStarted        = "server started, app=%s env=%s port=%s"
	LogServerStopped        = "server stopped, reason=%s"
	LogDBConnected          = "database connected, host=%s port=%s db=%s"
	LogDBMigrated           = "database migrated, tables=%d"
	LogDBSeedDone           = "database seed done, users=%d products=%d categories=%d"
	LogRedisConnected       = "redis connected, addr=%s"
	LogMinIOConnected       = "minio connected, endpoint=%s bucket=%s"
	LogUserRegistered       = "user registered, id=%d username=%s role=%s"
	LogUserLoggedIn         = "user logged in, id=%d username=%s role=%s"
	LogUserProfileUpdated   = "user profile updated, id=%d nickname=%s"
	LogPasswordChanged      = "password changed, user_id=%d"
	LogProductCreated       = "product created, id=%d name=%s price=%.2f stock=%d status=%s"
	LogProductUpdated       = "product updated, id=%d name=%s price=%.2f stock=%d status=%s"
	LogProductStatusChanged = "product status changed, id=%d status=%s operator=%d"
	LogProductViewed        = "product viewed, id=%d user_id=%d"
	LogCategoryCreated      = "category created, id=%d name=%s level=%d parent_id=%d"
	LogCartItemAdded        = "cart item added, user_id=%d product_id=%d quantity=%d"
	LogCartItemUpdated      = "cart item updated, user_id=%d item_id=%d quantity=%d"
	LogCartItemRemoved      = "cart item removed, user_id=%d item_id=%d"
	LogOrderCreated         = "order created, id=%d order_no=%s user_id=%d amount=%.2f status=%s"
	LogOrderPaid            = "order paid, id=%d order_no=%s pay_no=%s amount=%.2f status=%s"
	LogOrderCancelled       = "order cancelled, id=%d order_no=%s user_id=%d status=%s"
	LogOrderShipped         = "order shipped, id=%d order_no=%s tracking_no=%s status=%s"
	LogOrderCompleted       = "order completed, id=%d order_no=%s status=%s"
	LogCouponCreated        = "coupon template created, id=%d name=%s type=%s"
	LogCouponClaimed        = "coupon claimed, coupon_id=%d user_id=%d status=%s"
	LogReviewCreated        = "review created, id=%d user_id=%d product_id=%d rating=%d status=%s"
	LogReviewReplied        = "review replied, id=%d reply=%s"
	LogAuditRecorded        = "audit recorded, user_id=%d action=%s entity=%s entity_id=%s"
	LogUploadSucceeded      = "file uploaded, key=%s size=%d"
	LogRequestHandled       = "request handled, request_id=%s method=%s path=%s status=%d latency_ms=%d"
	LogAuthFailed           = "auth failed, request_id=%s path=%s reason=%s"
)
